### ISSUE TITLE
TypeError in merging nested array

### ISSUE THREAD

**Issue by jsanjay63** [tgknight/array-object-merge#7]
ErrorMessage:
TypeError: Cannot assign to read only property '0' of object '[object String]'

Sample program:
const mergeJSON = require('array-object-merge');
const json1 = {"id": "abc","publish_settings": {"bookmark": {"center": ["12","9"]}}};

const json2 = {"id": "abc","publish_settings": {"bookmark": {"center": ["10","8"]}}};
const jsonout = mergeJSON(json1, json2, 'id');
console.log(JSON.stringify(jsonout));

This error occurs when merging center array in the above object. If we have a nested object instead of array, like
const json3 = {"id": "abc","publish_settings": {"bookmark": {"id": "10"}}};
It merges successfully.

**Comment by tnptop** [comment]
My first guess is the package is trying to find the key `id` in the array `[12, 9]`, since it is designed to merge the value(s) of key(s) specified of the objects within arrays.

It thus lack supports for merging arrays of primitive values (which can be discussed further on desired behaviors of "merging" arrays; per REST spec everything should be replaced with the new one, thus the reason for using this package).

For now I'll make it behave like `Array.prototpye.concat`. I'll work on it when I have an access to my laptop.

Thanks for the heads up!

-----
P.S. Pro tip: enclose the code sample with three grave accents (\```)  to make the code more readable, as it is in `code` block of markdown:

```
const json = { a: 1, b: 2 }
```

**Comment by jsanjay63** [comment]
Yes, I believe everything replaced with the new array value would be desired behavior.
In the above case, this should be the output.
```
{"id": "abc","publish_settings": {"bookmark": {"center": ["10","8"]}}}
```
Thanks for looking into this issue.

**Comment by tnptop** [comment]
@jsanjay63 Please test the fix by pulling [this branch](https://github.com/tnptop/array-object-merge/tree/fix-primitive-array-merge) and replace your current version of the package.

**Comment by jsanjay63** [comment]
Done. Looks good !!
Thanks for the update.
